package thatonething.entities.enums;

public enum LiveEntityType {
    ANIMAL_VERY_LARGE,
    ANIMAL_LARGE,
    ANIMAL_MEDIUM,
    ANIMAL_SMALL,
    ANIMAL_VERY_SMALL,
    CUBOID_VERY_LARGE,
    CUBOID_LARGE,
    CUBOID_MEDIUM,
    CUBOID_SMALL,
    CUBOID_VERY_SMALL,
    HUMANOID_VERY_LARGE,
    HUMANOID_LARGE,
    HUMANOID_MEDIUM,
    HUMANOID_SMALL,
    HUMANOID_VERY_SMALL
}